export const MEAL_LIST_FAIL = 'MEAL_LIST_FAIL';
export const MEAL_LIST_SUCCESS = 'MEAL_LIST_SUCCESS';
export const MEAL_LIST_REQUEST = 'MEAL_LIST_REQUEST';

export const MEAL_DETAILS_FAIL = 'MEAL_DETAILS_FAIL';
export const MEAL_DETAILS_SUCCESS = 'MEAL_DETAILS_SUCCESS';
export const MEAL_DETAILS_REQUEST = 'MEAL_DETAILS_REQUEST';

export const MEAL_TOP_FAIL = 'MEAL_TOP_FAIL';
export const MEAL_TOP_SUCCESS = 'MEAL_TOP_SUCCESS';
export const MEAL_TOP_REQUEST = 'MEAL_TOP_REQUEST';